import {selectHistoryTask} from './history-selection'
import {test,expect} from '@playwright/test'

test('navigation groups, live results and stability workflow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#tasks')
 await expect(page.getByRole('heading',{name:'测评任务',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'新建测评任务',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.locator('select').nth(1).selectOption('loan-agent-v2-fixed')
 await dialog.getByLabel('任务测评集',{exact:true}).selectOption('loan-risk-policy')
 await expect(dialog.getByLabel('任务测评集版本',{exact:true})).toHaveValue('1')
 await dialog.locator('label').filter({hasText:'稳定性测试重复次数'}).locator('input').fill('3')
 await dialog.getByRole('button',{name:'提交测评',exact:true}).click()
 await expect(page).toHaveURL(/#stability\//)
 await expect(page.locator('tbody tr')).toHaveCount(3)
 await expect(page.locator('tbody tr').first()).toContainText('运行完成',{timeout:30000})
 await page.screenshot({path:'../runtime/browser-tests/stability.png',fullPage:true})
 await page.locator('tbody tr').first().getByRole('button',{name:'查看样本'}).click()
 await expect(page.getByRole('heading',{name:'测评报告',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'← 返回结果中心'}).click()
 await expect(page).toHaveURL(/#results$/)
 const sidebar=await page.locator('.sidebar').innerText()
 expect(sidebar.indexOf('结果中心')).toBeGreaterThan(sidebar.indexOf('分析与改进'))
 await expect(page.locator('tbody tr').first()).toBeVisible()
 expect(errors).toEqual([])
})

test('three evaluator editors and real source display',async({page})=>{
 await page.goto('/#evaluators')
 await page.locator('.evaluator-choice').filter({hasText:'Skill Routing'}).click()
 await page.getByRole('button',{name:'实现源码',exact:true}).click()
 await expect(page.locator('.source-code')).toContainText('class SkillRoutingEvaluator')
 await page.getByRole('button',{name:/LLM 评估器/}).click()
 await page.getByRole('button',{name:'新建评估器',exact:true}).click()
 await expect(page.getByRole('dialog').getByLabel('评分说明',{exact:true})).toBeVisible()
 await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.getByRole('button',{name:/复合评估器/}).click()
 await page.getByRole('button',{name:'新建评估器',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.getByRole('dialog')).toContainText('总权重：0.00% / 100%')
 await page.setViewportSize({width:1280,height:720})
 await page.evaluate(()=>Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{}))))
 const dialogBox=await page.getByRole('dialog').boundingBox()
 expect(dialogBox!.y).toBeGreaterThanOrEqual(0)
 expect(dialogBox!.y+dialogBox!.height).toBeLessThanOrEqual(720)
 await expect(page.getByRole('dialog').getByRole('button',{name:'保存草稿',exact:true})).toBeInViewport()
 expect(await page.locator('.el-dialog__body').evaluate(el=>el.scrollHeight>el.clientHeight)).toBeTruthy()
 await page.screenshot({path:'../runtime/browser-tests/composite.png',fullPage:true,animations:'disabled'})
})

test('Bad Case becomes a regression draft and review persists',async({page,request})=>{
 const launch=await request.post('/api/evaluations',{data:{version:'loan-agent-v1-risky',dataset_id:'loan-risk-policy',dataset_version:1}})
 expect(launch.ok()).toBeTruthy()
 const {run_id}=(await launch.json()).data
 await page.goto('/#results/'+run_id)
 await expect(page.getByRole('button',{name:'创建回归测评集草稿'})).toBeVisible({timeout:30000})
 await page.getByRole('button',{name:'创建回归测评集草稿'}).click()
 await page.getByRole('dialog').getByRole('button',{name:'创建草稿',exact:true}).click()
 await expect(page).toHaveURL(/#datasets\//)
 const generatedDatasetId=page.url().split('#datasets/')[1]
 await expect(page.locator('#dataset-workspace-title')).toContainText('回归测评集')
 await page.goto('/#optimizer/'+run_id)
 await expect(page.getByRole('heading',{name:'分析结果',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'查看关联原因与建议'}).first().click()
 await expect(page.getByRole('heading',{name:'怎么改',exact:true}).first()).toBeVisible()
 await expect(page.getByRole('heading',{name:'如何验证',exact:true}).first()).toBeVisible()
 await expect(page.locator('article').filter({has:page.getByRole('heading',{name:'怎么改',exact:true})}).first()).toContainText('优先级')
 await page.getByPlaceholder('填写姓名或工号（当前为人工声明）').fill('验收测试')
 await page.locator('article select').first().selectOption('confirmed')
 await page.locator('article').filter({has:page.getByRole('button',{name:'保存复核'})}).first().getByRole('button',{name:'保存复核'}).click()
 await page.getByRole('dialog').locator('textarea').fill('已根据 Trace 核对本次测试证据')
 await page.getByRole('dialog').getByRole('button',{name:'保存状态',exact:true}).click()
 await expect(page.getByText('复核状态已保存',{exact:true})).toBeVisible()
 await page.reload()
 await page.getByRole('button',{name:'查看关联原因与建议'}).first().click()
 await expect(page.locator('article select').first()).toHaveValue('confirmed')
 await page.screenshot({path:'../runtime/browser-tests/review.png',fullPage:true})
 await request.delete('/api/datasets/'+generatedDatasetId)
})

test('selectable mock evaluators and static analysis steps',async({page})=>{
 await page.goto('/#evaluators')
 for(const kind of ['LLM 评估器','复合评估器']){
  await page.getByRole('button',{name:new RegExp(kind)}).click()
  await expect(page.locator('.evaluator-list .evaluator-choice').filter({hasText:'Mock'})).toHaveCount(1)
  await page.locator('.evaluator-list .evaluator-choice').filter({hasText:'Mock'}).click()
  await page.getByLabel('选择 Mock 案例').selectOption('fail')
  await expect(page.getByTestId('mock-evaluator-output')).toContainText('"outcome": "fail"')
  await page.getByLabel('选择 Mock 案例').selectOption('error')
  await expect(page.getByTestId('mock-evaluator-output')).toContainText('"score": null')
  await page.getByRole('button',{name:'样例配置',exact:true}).click()
  await expect(page.getByRole('heading',{name:'评分规则',exact:true})).toBeVisible()
 }
 await page.goto('/#analysis')
 await page.getByLabel('检查对象',{exact:true}).selectOption('loan-agent-v1-risky')
 await expect(page.getByRole('heading',{name:'第二步：确认要检查的技能职责'})).toBeVisible()
 await expect(page.locator('tbody tr')).toHaveCount(4)
 await page.getByRole('button',{name:'查看演示样例',exact:true}).click()
 await page.getByRole('button',{name:'展示样例',exact:true}).click()
 await expect(page.getByRole('heading',{name:'第三步：查看问题与修改建议'})).toBeVisible()
 await expect(page.getByText('演示 · 高风险审批缺少人工复核约束',{exact:true})).toBeVisible()
 await page.screenshot({path:'../runtime/browser-tests/static-steps.png',fullPage:true})
})

test('static analysis click shows pending and actionable server failure',async({page})=>{
 await page.route('**/api/skill-analysis/capability',route=>route.fulfill({json:{code:'0',message:'success',data:{configured:true,reason:null}}}))
 let requests=0
 let release!:()=>void
 const gate=new Promise<void>(resolve=>{release=resolve})
 await page.route('**/api/evaluations/skill-analysis',async route=>{
  requests++;await gate
  await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:'1',message:'Skill analysis is unavailable',data:null})})
 })
 await page.goto('/#analysis')
 await page.getByLabel('检查对象',{exact:true}).selectOption('loan-agent-v1-risky')
 await page.getByRole('button',{name:'运行分析',exact:true}).click()
 await expect(page.getByRole('status').filter({hasText:'请求已发出'})).toBeVisible()
 await expect(page.getByRole('button',{name:'正在处理…',exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:'查看演示样例',exact:true})).toBeDisabled()
 await expect(page.getByLabel('检查对象',{exact:true})).toBeDisabled()
 release()
 await expect(page.getByRole('alert').filter({hasText:'未能完成分析'})).toBeInViewport()
 await expect(page.getByRole('alert').filter({hasText:'未能完成分析'})).toContainText('HTTP 503')
 await expect(page.getByRole('button',{name:'运行分析',exact:true})).toBeEnabled()
 expect(requests).toBe(1)
 await expect(page.getByRole('heading',{name:'分析结果',exact:true})).toHaveCount(0)
})

test('examples, dataset sample loading and meaningful AB selection',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#evaluators')
 await page.getByRole('button',{name:/LLM 评估器/}).click()
 await page.locator('.evaluator-list .evaluator-choice').filter({hasText:'Mock'}).click()
 await expect(page.getByRole('heading',{name:'LLM 评分输出样例'})).toBeVisible()
 await page.getByRole('button',{name:/复合评估器/}).click()
 await page.locator('.evaluator-list .evaluator-choice').filter({hasText:'Mock'}).click()
 await expect(page.getByText('计算：100 × 40% + 80 × 60% = 88.0 分')).toBeVisible()
 await page.getByLabel('假设有阻断规则失败').check()
 await expect(page.getByText(/未通过：阻断规则失败/)).toBeVisible()
 await page.goto('/#analysis')
 await page.getByRole('button',{name:'查看演示样例',exact:true}).click()
 await page.getByLabel('检查对象',{exact:true}).selectOption('loan-agent-v1-risky')
 await page.getByRole('button',{name:'展示样例',exact:true}).click()
 await expect(page.locator('#analysis-item-mock-approval')).toBeVisible()
 await page.getByPlaceholder('填写姓名或工号（当前为人工声明）').fill('样例复核')
 await page.locator('#analysis-item-mock-approval select').selectOption('confirmed')
 await page.getByRole('button',{name:'保存复核'}).click()
 await expect(page.getByText(/演示复核，仅本页展示，不写入服务端/)).toBeVisible()
 const created=await request.post('/api/datasets',{data:{name:'交互测试样例-'+Date.now()}})
 const dataset=(await created.json()).data.dataset
 try{
  await page.goto('/#datasets/'+dataset.id)
  await page.getByRole('button',{name:'新增用例',exact:true}).click()
  await page.getByTestId('case-name').fill('手动样例')
  await page.getByTestId('turn-input-0').fill('{"query":"测试"}')
  await page.getByTestId('save-case').click()
  await expect(page.getByText('用例已保存到草稿',{exact:true})).toBeVisible()
 }finally{await request.delete('/api/datasets/'+dataset.id)}
 await page.goto('/#experiments')
 await expect(page.getByRole('combobox',{name:'实验A已完成任务'})).toBeEnabled()
 await expect(page.getByRole('combobox',{name:'实验B已完成任务'})).toBeDisabled()
 const runIds:string[]=[]
 for(const version of ['loan-agent-v1-risky','loan-agent-v2-fixed']){
  const launched=await request.post('/api/evaluations',{data:{version,dataset_id:'loan-risk-policy',dataset_version:1}})
  expect(launched.ok()).toBeTruthy()
  const {run_id}=(await launched.json()).data;runIds.push(run_id)
  await expect.poll(async()=>{const response=await request.get('/api/runs/'+run_id+'/status');return (await response.json()).data.status},{timeout:30000}).toBe('completed')
 }
 await page.getByRole('button',{name:'刷新任务',exact:true}).click()
 for(let i=0;i<2;i++)await selectHistoryTask(page,i,runIds[i])
 await expect(page.getByRole('heading',{name:'逐项结果变化',exact:true})).toBeVisible()
 await expect(page.locator('td').filter({hasText:/^改善$/}).first()).toBeVisible()
 expect(errors).toEqual([])
 await page.screenshot({path:'../runtime/browser-tests/ab-choice.png',fullPage:true})
})
