import {test,expect} from '@playwright/test'

test('Submission errors remain visible at the bottom and retry after correction sends a request',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 let submissions=0
 await page.route('**/api/bank-evaluations',async route=>{
  submissions++
  await route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({detail:'智能体配置已变化，请刷新后重新提交'})})
 })
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'发起测评',exact:true}).click()
 const form=page.getByRole('dialog',{name:'新建测评任务'})
 const start=form.getByRole('button',{name:'开始测评',exact:true})
 const footer=form.locator('.el-dialog__footer')
 await form.getByRole('spinbutton',{name:'稳定性测试',exact:true}).scrollIntoViewIfNeeded()
 await start.click()
 await expect(footer.getByRole('alert')).toContainText('尚未选择评估器')
 await expect(footer.getByRole('alert')).toBeInViewport()
 expect(submissions).toBe(0)
 await footer.getByRole('button',{name:'采用推荐评估器',exact:true}).click()
 await expect(footer.getByRole('alert')).toHaveCount(0)
 await form.getByRole('spinbutton',{name:'稳定性测试',exact:true}).fill('21')
 await start.click()
 await expect(footer.getByRole('alert')).toContainText('1—20')
 await expect(footer.getByRole('alert')).toBeInViewport()
 expect(submissions).toBe(0)
 await form.getByRole('spinbutton',{name:'稳定性测试',exact:true}).fill('1')
 await start.click()
 await expect(footer.getByRole('alert')).toContainText('智能体配置已变化')
 await expect(footer.getByRole('alert')).toBeInViewport()
 await expect(start).toBeEnabled()
 expect(submissions).toBe(1)
 await page.setViewportSize({width:390,height:844})
 await expect(footer.getByRole('alert')).toBeInViewport()
 await expect(start).toBeInViewport()
 expect(errors).toEqual([])
})

test('Only cloudshrimp uses a Git branch between agent ID and version',async({page,request})=>{
 const catalog=await(await request.get('/api/bank-targets')).json()
 const current=catalog.find((t:any)=>t.snapshot.invocation_config.mode==='cloudshrimp').git_branch_url
 expect(current).toContain('/tree/')
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'发起测评',exact:true}).click()
 const form=page.getByRole('dialog',{name:'新建测评任务'})
 const agent=form.getByRole('combobox',{name:'智能体',exact:true})
 const branch=form.getByRole('combobox',{name:'Git 仓库分支地址',exact:true})
 const version=form.getByRole('combobox',{name:'智能体版本',exact:true})
 await agent.selectOption('base')
 await expect(branch).toHaveCount(0)
 await expect(agent.locator('option:checked')).toContainText('loan-base')
 const baseBoxes=await Promise.all([agent.boundingBox(),version.boundingBox()])
 expect(baseBoxes[0]!.x+baseBoxes[0]!.width).toBeLessThan(baseBoxes[1]!.x)
 await agent.selectOption('workflow')
 await expect(branch).toHaveCount(0)
 await expect(agent.locator('option:checked')).toContainText('loan-workflow')
 await agent.selectOption('cloudshrimp')
 await expect(branch).toHaveValue(current)
 await expect(form.locator('.git-branch-field')).toContainText('客户分支查询接口待核实接入')
 const boxes=await Promise.all([agent.boundingBox(),branch.boundingBox(),version.boundingBox()])
 expect(boxes[0]!.x+boxes[0]!.width).toBeLessThan(boxes[1]!.x)
 expect(boxes[1]!.x+boxes[1]!.width).toBeLessThan(boxes[2]!.x)
 await expect(form.locator('datalist option')).toHaveAttribute('value',current)
 const graph=form.getByRole('region',{name:'测评对象来源与图谱'})
 await expect(graph.getByRole('button',{name:/^Subagent /})).toHaveCount(3)
 await branch.fill('https://example.test/unregistered/tree/new')
 await expect(version).toBeDisabled()
 await expect(graph).toHaveCount(0)
 await expect(form.getByRole('button',{name:'开始测评',exact:true})).toBeDisabled()
 await expect(form.getByRole('alert')).toContainText('未匹配')
 await branch.fill(current+'/')
 await expect(version).toBeEnabled()
 await expect(graph).toBeVisible()
 await branch.fill('https://example.test/unregistered/tree/new')
 await agent.selectOption('base')
 await expect(branch).toHaveCount(0)
 await expect(version).toBeEnabled()
 await expect(graph).toBeVisible()
 await form.getByRole('button',{name:'选择云虾：查看 Agent → Subagent → Skill → Tool',exact:true}).click()
 await expect(agent).toHaveValue('cloudshrimp')
 await expect(graph.getByRole('button',{name:/^Subagent /})).toHaveCount(3)
 await expect(graph.getByRole('button',{name:/^Skill /})).toHaveCount(3)
 await graph.getByRole('button',{name:'Subagent 进度查询 Agent',exact:true}).click()
 await expect(graph.locator('.node-detail')).toContainText('只读')
 await form.locator('.target-choice').evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}))
 await expect(branch).toBeInViewport()
 await page.screenshot({path:'runtime/target-branch-form.png'})
 await graph.locator('.graph-scroll').screenshot({path:'runtime/target-branch-cloud.png'})
 await page.setViewportSize({width:390,height:844})
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await agent.selectOption('demo')
 await expect(branch).toHaveCount(0)
 expect(errors).toEqual([])
})
