import {test,expect,type APIRequestContext} from '@playwright/test'
import { passAuthGate } from './auth-gate';
test.setTimeout(60000)
test.use({actionTimeout:8000})
async function json(r:any){expect(r.ok(),await r.text()).toBeTruthy();return r.json().then(j=>j.data)}
async function waitRun(request:APIRequestContext,id:string){
 await expect.poll(async()=> (await (await request.get('/api/runs/'+id+'/status')).json()).data.status,{timeout:60000,intervals:[500,1000,2000]}).toBe('completed')
 return json(await request.get('/api/runs/'+id))
}
test.beforeEach(async ({ page }) => {
  await page.goto('/');
  await passAuthGate(page);
});

test('live upstream: drafts, published versions, scoped evaluation, AB and writeback',async({page,request})=>{
 const errors:string[]=[],bad:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)bad.push(r.status()+' '+r.url())})
 const created=await json(await request.post('/api/datasets/loan-risk-policy/copy',{data:{name:'联调演示 · 三版本 '+Date.now(),source_version:1}}))
 const id=created.dataset.id,original=created.draft.cases[0]
 for(let i=1;i<3;i++)await json(await request.post('/api/datasets/'+id+'/drafts/cases',{data:{...original,id:'integration-case-'+i,name:'联调用例 '+i}}))
 for(let version=1;version<=3;version++){
  if(version>1)await json(await request.post('/api/datasets/'+id+'/drafts',{data:{based_on_version:version-1}}))
  await json(await request.post('/api/datasets/'+id+'/drafts/publish'))
 }
 await page.goto('/#datasets/'+id)
 await page.getByTestId('version-published-3').click()
 await page.getByTestId('run-dataset-version').click()
 const dialog=page.getByRole('dialog',{name:'新建测评任务'})
 await expect(dialog.getByLabel('任务测评集版本',{exact:true})).toBeEnabled()
 await dialog.getByLabel('任务测评集版本',{exact:true}).selectOption('2')
 await dialog.getByRole('button',{name:'清空选择',exact:true}).click()
 await expect(dialog.getByText('评估器 · 已选 0 个',{exact:true})).toBeVisible()
 await dialog.getByRole('button',{name:'全选可用项',exact:true}).click()
 await expect(dialog.getByText('推荐理由：',{exact:false}).first()).toBeVisible()
 await dialog.getByLabel('运行范围',{exact:true}).selectOption('selected')
 await dialog.getByRole('combobox',{name:'指定用例',exact:true}).locator('xpath=ancestor::div[contains(@class,"el-select__wrapper")]').click()
 await page.getByRole('option',{name:'联调用例 1',exact:true}).click()
 await page.keyboard.press('Escape')
 await expect(dialog.getByText('检查覆盖情况',{exact:false})).toHaveCount(0)
 const response=page.waitForResponse(r=>r.url().endsWith('/api/evaluations')&&r.request().method()==='POST')
 await dialog.getByRole('button',{name:'开始测评',exact:true}).click()
 const run=await json(await response)
 const report=await waitRun(request,run.run_id)
 expect(report.run.manifest.dataset.version).toBe(2)
 expect(report.run.manifest.selected_case_ids).toEqual(['integration-case-1'])
 await page.goto('/#results/'+run.run_id)
 await expect(page.getByRole('heading',{name:'评估结论',exact:true})).toBeVisible({timeout:15000})
 await page.getByRole('button',{name:'使用原配置重跑'}).click()
 await expect(page.getByRole('dialog',{name:'确认原配置重跑'}).getByRole('button',{name:'确认创建新任务'})).toBeEnabled()
 await page.getByRole('dialog',{name:'确认原配置重跑'}).getByRole('button',{name:'取消',exact:true}).click()
 await expect(page.getByRole('button',{name:'回写失败用例到草稿'})).toBeVisible()
 await page.getByRole('button',{name:'回写失败用例到草稿'}).click()
 await page.getByRole('button',{name:'确认回写',exact:true}).click()
 await expect(page).toHaveURL(new RegExp('datasets/'+id))
 const draft=await json(await request.get('/api/datasets/'+id+'/drafts/current'))
 expect(draft.based_on_version).toBe(3)
 await expect(page.getByTestId('run-dataset-version')).toBeDisabled()
 await page.getByTestId('case-name').fill('已通过界面保存的用例')
 await page.getByRole('button',{name:'保存草稿',exact:true}).click()
 await expect(page.getByText('草稿已保存',{exact:false}).first()).toBeVisible()
 expect((await json(await request.get('/api/datasets/'+id+'/drafts/current'))).cases.some((c:any)=>c.name==='已通过界面保存的用例')).toBeTruthy()
 const pair=await json(await request.post('/api/run-comparisons',{data:{baseline_version:'loan-agent-v1-risky',candidate_version:'loan-agent-v2-fixed',dataset_id:id,dataset_version:3,evaluators:[{id:'skill-routing',version:'1'},{id:'forbidden-tool',version:'1'}]}}))
 await waitRun(request,pair.baseline.run_id);await waitRun(request,pair.candidate.run_id)
 const comparison=await json(await request.get('/api/run-comparisons?baseline_run_id='+pair.baseline.run_id+'&candidate_run_id='+pair.candidate.run_id))
 expect(comparison.overall_score_delta).toBeGreaterThan(0)
 await page.goto('/#experiments')
 await expect(page.getByRole('button',{name:'创建实验并运行',exact:true})).toBeVisible()
 await page.getByRole('combobox',{name:'实验A已完成任务',exact:true}).locator('xpath=ancestor::div[contains(@class,"el-select__wrapper")]').click()
 await page.getByRole('listbox',{name:'实验A已完成任务',exact:true}).getByTestId('run-option-'+pair.baseline.run_id).click()
 await page.getByRole('combobox',{name:'实验B已完成任务',exact:true}).locator('xpath=ancestor::div[contains(@class,"el-select__wrapper")]').click()
 await page.getByRole('listbox',{name:'实验B已完成任务',exact:true}).getByTestId('run-option-'+pair.candidate.run_id).click()
 await expect(page.getByText('分数差（B − A）',{exact:true})).toBeVisible()
 await page.screenshot({path:'../runtime/integration-ab.png',fullPage:true})
 expect(errors).toEqual([]);expect(bad).toEqual([])
})
test('live upstream: evaluator config import, publish, disable, version diff and launch',async({page,request})=>{
 const base=(await json(await request.get('/api/evaluators/skill-routing'))).latest
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#evaluators')
 await page.getByRole('button',{name:'导入评估器',exact:true}).click()
 const name='联调导入规则 '+Date.now()
 await page.getByLabel('评估器配置文件').setInputFiles({name:'rule.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({name,draft:base}))})
 await page.getByRole('button',{name:'导入为草稿',exact:true}).click()
 await page.getByRole('button').filter({has:page.getByText(name,{exact:true})}).click()
 const item=(await json(await request.get('/api/evaluators?include_disabled=true'))).find((e:any)=>e.name===name)
 await json(await request.post('/api/evaluators/'+item.id+'/drafts/publish'))
 await json(await request.post('/api/evaluators/'+item.id+'/drafts',{data:{based_on_version:'1'}}))
 await json(await request.put('/api/evaluators/'+item.id+'/drafts/current',{data:{kind:base.kind,dimension:base.dimension,metric:'routing_revision',severity:base.severity,implementation_id:base.implementation_id,implementation_version:base.implementation_version,config:base.config,children:[],combination:null}}))
 await json(await request.post('/api/evaluators/'+item.id+'/drafts/publish'))
 await page.goto('/#evaluators/'+item.id)
 await page.getByText('版本差异',{exact:true}).click()
 await page.getByLabel('对比原版本').selectOption('1');await page.getByLabel('对比新版本').selectOption('2')
 await expect(page.getByText('routing_revision',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'启用',exact:true}).click()
 await expect(page.getByRole('button',{name:'禁用',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'禁用',exact:true}).click()
 await expect(page.getByRole('button',{name:'启用',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'发起测评',exact:true})).toBeDisabled()
 await page.getByRole('button',{name:'启用',exact:true}).click()
 await page.getByRole('button',{name:'发起测评',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'新建测评任务'}).getByText('评估器 · 已选 1 个',{exact:true})).toBeVisible()
 expect(errors).toEqual([])
})
