import { test, expect } from '@playwright/test'

test('creating from a target drawer returns to its filtered source', async ({ page }) => {
  await page.goto('/preview/targets?type=Agent')
  await page.getByRole('button', { name: '查看版本与定义 →', exact: true }).first().click()
  const drawer = page.getByRole('dialog', { name: '测评对象详情', exact: true })
  await drawer.getByRole('link', { name: '配置测评', exact: true }).click()
  await expect(page.getByRole('link', { name: '返回来源页面', exact: true })).toHaveAttribute('href', '/preview/targets?type=Agent')
  await page.getByRole('link', { name: '返回来源页面', exact: true }).click()
  await expect(drawer).toBeVisible()
  await expect(page).toHaveURL(/\/preview\/targets\?type=Agent$/)
})

test('full evidence returns to its source task and rejects external return destinations', async ({ page }) => {
  const source = '/preview/analysis?tab=dynamic&q=贷款'
  await page.goto(`/preview/runs/run-baseline/cases/case-01?returnTo=${encodeURIComponent(source)}`)
  const back = page.getByRole('link', { name: '返回来源页面（保留筛选）' })
  await expect(back).toHaveAttribute('href', source)
  await back.click()
  await expect(page).toHaveURL(new URL(source, page.url()).href)
  await page.goto('/preview/runs/run-baseline/cases/case-01?returnTo=https%3A%2F%2Fexample.com')
  await expect(page.getByRole('link', { name: '返回来源页面（保留筛选）' })).toHaveAttribute('href', '/preview/runs/run-baseline')
})

test('review drawer protects unsaved input on next and close without losing the report', async ({ page }) => {
  await page.goto('/preview/runs/run-baseline')
  const openers = page.getByRole('button', { name: '查看证据与复核 →', exact: true })
  await expect(openers.first()).toBeVisible()
  const parentUrl = page.url()
  await openers.first().click()
  const drawer = page.getByRole('dialog', { name: '用例证据与复核', exact: true })
  await expect(drawer).toBeVisible()
  await expect(page).toHaveURL(parentUrl)
  const reason = drawer.getByRole('textbox', { name: '复核理由' })
  await reason.fill('尚未保存的证据判断')
  await drawer.getByRole('button', { name: '下一条', exact: true }).click()
  await page.getByRole('button', { name: '继续复核', exact: true }).click()
  await expect(reason).toHaveValue('尚未保存的证据判断')
  await drawer.getByRole('button', { name: '关闭此对话框' }).click()
  await page.getByRole('button', { name: '继续复核', exact: true }).click()
  await expect(reason).toHaveValue('尚未保存的证据判断')
  await drawer.getByRole('button', { name: '关闭此对话框' }).click()
  await page.getByRole('button', { name: '放弃并离开', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  await expect(openers.first()).toBeFocused()
  await expect(page).toHaveURL(parentUrl)
})

test('return from full evidence restores the report scroll position', async ({ page }) => {
  await page.goto('/preview/runs/run-baseline')
  const opener = page.getByRole('button', { name: '查看证据与复核 →', exact: true }).last()
  await opener.scrollIntoViewIfNeeded()
  const parentUrl = page.url()
  const position = await page.evaluate(() => window.scrollY)
  expect(position).toBeGreaterThan(0)
  await opener.click()
  const evidencePath = await page.getByRole('dialog', { name: '用例证据与复核', exact: true }).getByRole('link', { name: '全页打开', exact: true }).getAttribute('href')
  await page.getByRole('dialog', { name: '用例证据与复核', exact: true }).getByRole('link', { name: '全页打开', exact: true }).click()
  await expect(page).toHaveURL(/\/cases\//)
  await page.reload()
  await page.getByRole('link', { name: '返回来源页面（保留筛选）' }).click()
  await expect(page).toHaveURL(parentUrl)
  const restored = page.getByRole('dialog', { name: '用例证据与复核', exact: true })
  await expect(restored).toBeVisible()
  await expect(restored.getByRole('link', { name: '全页打开', exact: true })).toHaveAttribute('href', evidencePath!)
  await restored.getByRole('button', { name: '关闭此对话框' }).click()
  await expect.poll(async () => Math.abs(await page.evaluate(() => window.scrollY) - position)).toBeLessThan(5)
})

test('asset drawers keep list filters and protect edited evaluator versions', async ({ page }) => {
  await page.goto('/preview/targets?type=Agent')
  const targetOpener = page.getByRole('button', { name: '查看版本与定义 →', exact: true }).first()
  await targetOpener.click()
  const target = page.getByRole('dialog', { name: '测评对象详情', exact: true })
  await expect(target.getByRole('combobox', { name: '对象版本', exact: true })).toBeVisible()
  const targetUrl = page.url()
  await target.getByRole('combobox', { name: '对象版本', exact: true }).press('Enter')
  await page.getByRole('option').nth(1).click()
  await expect(page).toHaveURL(targetUrl)
  await expect(target.getByRole('link', { name: '全页打开', exact: true })).toHaveAttribute('href', /version=/)
  const selectedVersionPath = await target.getByRole('link', { name: '全页打开', exact: true }).getAttribute('href')
  await target.getByRole('link', { name: '全页打开', exact: true }).click()
  await page.reload()
  await page.getByRole('link', { name: '返回来源页面', exact: true }).click()
  await expect(page).toHaveURL(targetUrl)
  await expect(target).toBeVisible()
  await expect(target.getByRole('link', { name: '全页打开', exact: true })).toHaveAttribute('href', selectedVersionPath!)
  await target.getByRole('button', { name: '关闭此对话框' }).click()
  await expect(targetOpener).toBeFocused()

  await page.goto('/preview/evaluators')
  const opener = page.getByRole('button', { name: '查看配置与试评', exact: true }).first()
  await opener.click()
  const evaluator = page.getByRole('dialog', { name: '评估器详情', exact: true })
  await evaluator.getByRole('button', { name: '编辑并发布新版本', exact: true }).click()
  await evaluator.getByRole('textbox', { name: '版本说明（发布时必填）', exact: true }).fill('待核对的标准修改')
  await evaluator.getByRole('button', { name: '下一条', exact: true }).click()
  await page.getByRole('button', { name: '继续编辑', exact: true }).click()
  await expect(evaluator.getByRole('textbox', { name: '版本说明（发布时必填）', exact: true })).toHaveValue('待核对的标准修改')
  await expect(page).toHaveURL(/\/preview\/evaluators$/)
  await evaluator.getByRole('button', { name: '关闭此对话框' }).click()
  await page.getByRole('button', { name: '放弃修改', exact: true }).click()
  await expect(opener).toBeFocused()

  await page.goto('/preview/datasets')
  const datasetOpener = page.getByRole('button', { name: '查看用例与版本', exact: true }).first()
  await datasetOpener.click()
  const dataset = page.getByRole('dialog', { name: '测评集详情', exact: true })
  await expect(dataset.getByRole('combobox', { name: '测评集版本', exact: true })).toBeVisible()
  await expect(page).toHaveURL(/\/preview\/datasets$/)
  await dataset.getByRole('button', { name: '下一条', exact: true }).click()
  await expect(dataset.getByRole('button', { name: '上一条', exact: true })).toBeEnabled()
  await dataset.getByRole('button', { name: '关闭此对话框' }).click()
  await expect(datasetOpener).toBeFocused()
})
