import { test, expect } from '@playwright/test'

test('historical comparison explains changed inputs with business-readable preflight and preserves all sample buckets', async ({
  page,
}) => {
  await page.goto('/preview/comparisons?create=1&baseline=run-baseline')
  await page.getByLabel('候选运行 B（可多选，分别对基线）', { exact: true }).press('Enter')
  await page.getByRole('option', { name: /新测评集下的候选验证/ }).click()
  await page.getByLabel('候选运行 B（可多选，分别对基线）', { exact: true }).press('Escape')
  await page.getByRole('button', { name: '生成已有结果对比', exact: true }).click()
  await expect(page).toHaveURL(/\/preview\/comparisons\/cmp-/)
  await expect(page.getByText(/控制变量存在差异/).first()).toBeVisible()
  const execution = page
    .locator('table')
    .first()
    .getByRole('row')
    .filter({ has: page.getByRole('rowheader', { name: '执行参数', exact: true }) })
  await expect(execution.locator('td').first()).toContainText('并发数4')
  await expect(execution.locator('td').first()).toContainText('超时60 秒')
  await expect(execution.locator('td').first()).toContainText('重试上限1')
  await expect(execution.locator('td').first()).toContainText('采样率100%')
  await expect(page.getByRole('button', { name: /仅 A 1/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /仅 B 1/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /未配对 1/ })).toBeVisible()
  await page.getByRole('button', { name: /未配对 1/ }).click()
  await page.reload()
  await expect(page).toHaveURL(/group=unpaired/)
  await expect(page.getByText(/仅描述性比较/).first()).toBeVisible()
})

test('static analysis failure is retained, retry produces evidence, and risk can lead to dataset preparation', async ({
  page,
}) => {
  await page.goto('/preview/analysis?target=agent-service&version=v1')
  await page.locator('.scenario-label').getByRole('combobox').press('Enter')
  await page.getByRole('option', { name: /模拟检查服务失败/ }).click()
  await page.getByRole('button', { name: '检查此版本定义（Mock）', exact: true }).click()
  await expect(page.getByRole('button', { name: '重试检查（保留失败记录）' })).toBeVisible()
  await page.getByRole('button', { name: '重试检查（保留失败记录）' }).click()
  await expect(page.getByText(/办理与咨询边界可能重叠/).first()).toBeVisible()
  const riskCard = page.locator('.static-risk').first()
  await expect(riskCard.locator('.risk-evidence')).toContainText('职责描述')
  await expect(riskCard.locator('pre')).toBeHidden()
  await riskCard.getByText('查看分析时保留的完整定义片段', { exact: true }).click()
  await expect(riskCard.locator('.ux-value-record').first()).toBeVisible()
  await riskCard.getByText('查看分析时保留的完整定义片段', { exact: true }).click()
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('agentgate.preview.v2')!))
  expect(data.analyses).toHaveLength(2)
  expect(data.analyses.some((a: { status: string }) => a.status === 'failed')).toBe(true)
  await page.reload()
  await expect(page.getByText(/办理与咨询边界可能重叠/).first()).toBeVisible()
  await page.getByRole('link', { name: '补充风险验证用例', exact: true }).first().click()
  await expect(page).toHaveURL(/sourceAnalysis=/)
  await expect(page.getByText(/已带入静态风险/)).toBeVisible()
  await page.getByRole('button', { name: '新增用例', exact: true }).click()
  await page
    .getByLabel('用户输入（必填）', { exact: true })
    .fill('我想提交贷款申请，同时了解办理条件')
  await page.getByLabel('预期表现', { exact: true }).fill('澄清意图，完成必要校验后办理')
  await page.getByRole('button', { name: '应用用例修改', exact: true }).click()
  await expect(page.getByRole('heading', { name: '用例（1）', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '查看来源静态分析', exact: true })).toBeVisible()
  await page.getByLabel('测评集名称（必填）', { exact: true }).fill('静态风险验证集')
  await page
    .locator('label.el-checkbox')
    .filter({ hasText: '已审阅全部用例，并核对期望、变量、文件和 Agent 上下文适配' })
    .click()
  await page.getByRole('button', { name: '保存草稿，继续发布', exact: true }).click()
  await page.getByPlaceholder('说明修订原因及主要变化').fill('补充静态风险验证场景')
  await page.getByRole('button', { name: '发布新版本', exact: true }).click()
  await page.getByRole('button', { name: '使用此版本并返回', exact: true }).click()
  await expect(page).toHaveURL(/\/preview\/analysis\?.*datasetVersion=1/)
  await page.getByRole('link', { name: '使用补充用例进行测评', exact: true }).click()
  await expect(page).toHaveURL(/\/preview\/runs\/new\?/)
  await expect(page.getByRole('button', { name: '提交测评', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '提交测评', exact: true }).click()
  await expect(page).toHaveURL(/\/preview\/runs\/run-/)
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('agentgate.preview.v2')!))
  const runId = new URL(page.url()).pathname.split('/').pop()
  const run = saved.runs.find((item: { id: string }) => item.id === runId)
  expect(run.cases).toHaveLength(1)
  expect(run.cases[0].sources.some((source: string) => source.includes('analysis='))).toBe(true)
})
