import { test, expect } from '@playwright/test'
test('structured values preserve zero, false, null and nested lists; nested invalid input blocks save', async ({ page }) => {
  await page.goto('/tests/fixtures/structured-input.html')
  await expect(page.getByRole('heading', { name: '字段编辑行为验证' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '高级 JSON 内容', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const output = page.getByLabel('保存结果')
  expect(JSON.parse(await output.innerText())).toEqual({ count: 0, enabled: false, missing: null, nested: { code: 'keep' }, items: [0, false, null] })
  await page.getByRole('button', { name: '添加变量 4 值', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存', exact: true })).toBeDisabled()
  await page.getByRole('textbox', { name: '变量 4 值 2 名称', exact: true }).fill('code')
  await expect(page.getByText('变量名称重复，请分别命名。')).toBeVisible()
  await page.getByRole('textbox', { name: '变量 4 值 2 名称', exact: true }).fill('extra')
  await page.getByRole('textbox', { name: '变量 4 值 2 值', exact: true }).fill('new')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  expect(JSON.parse(await output.innerText()).nested).toEqual({ code: 'keep', extra: 'new' })
  const readonly = page.getByRole('region', { name: '只读内容' })
  await expect(readonly).toContainText('否')
  await expect(readonly).toContainText('未提供')
  await expect(readonly.locator('pre')).toHaveCount(0)
})
test('changing a populated value type can be cancelled without losing content', async ({ page }) => {
  await page.goto('/tests/fixtures/structured-input.html')
  await page.getByRole('combobox', { name: '变量 4 值 1 值类型', exact: true }).press('Enter')
  await page.getByRole('option', { name: '数字', exact: true }).click()
  await page.getByRole('button', { name: '保留原值', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '变量 4 值 1 值', exact: true })).toHaveValue('keep')
})
